name: pull-request
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  call-test:
    uses: ./.github/workflows/test.yml
    with:
      enable_android: false
      enable_web: false
      enable_ios: false
      enable_windows: ${{ github.event.pull_request.draft == false }}
      enable_linux: false
      enable_macos: false
